services:
  - name: api-service
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    healthCheckPath: /docs        # opcional, tu API responde 200 aquí

  - name: socket-service
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.sockets.realtime:socket_app --host 0.0.0.0 --port $PORT"
    web:
      websocketSupport: true
    autoDeploy: true
